package MCalculadora;


/**
* MCalculadora/ICalculadoraOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculadora.idl
* domingo 20 de marzo de 2022 23H01' CET
*/

public interface ICalculadoraOperations 
{
  double sumar (MCalculadora.Operadores Ops);
  double restar (MCalculadora.Operadores Ops);
  double multiplicar (MCalculadora.Operadores Ops);
  double dividir (MCalculadora.Operadores Ops);
} // interface ICalculadoraOperations
