package MCalculadora;


/**
* MCalculadora/Operadores.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculadora.idl
* domingo 20 de marzo de 2022 23H01' CET
*/

public final class Operadores implements org.omg.CORBA.portable.IDLEntity
{
  public double a = (int)0;
  public double b = (int)0;

  public Operadores ()
  {
  } // ctor

  public Operadores (int _a, int _b)
  {
    a = _a;
    b = _b;
  } // ctor

} // class Operadores
